### PR TITLE
Updated eigen3-hdf5 to work with 1.8 and 1.10

### PR DESCRIPTION
**Pull request by Gjacquenot**

### CODE REVIEW

**Comment by garrison** [comment]
Thanks.  Can you provide some more context for this?  I am assuming 1.8 and 1.10 are versions of the HDF5 library?  (Is eigen3-hdf5 currently broken on 1.10?)

I think your change to the travis file is actually resulting in it using an older, unsupported version of the hdf5 library.

**Comment by Gjacquenot** [comment]
Hello @garrison . Yes it is broken with 1.10. I try to have it working with both versions, but I have some compilations issues as you can see from the log of travis

**Comment by garrison** [comment]
I have little interest in this package anymore, but I would be happy to merge a pull request if you can get it working.  Ideally it will work on hdf5 1.8.12 or higher.  (There is probably little reason to support older versions in the 1.8 series since eigen3-hdf5 currently does not support them.)  Alternatively, the library could simply require 1.10 or higher going forward.

**Comment by Gjacquenot** [comment]
Well, commit 5accaef works with 1.10. I would like to find the solution to work with both versions.

To be more accurate, the following test pass

    TEST(MatrixRoundTrip, Double) {
        Eigen::MatrixXd mat(3, 4), mat2;
        mat << 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12;
        {
            H5::H5File file("test_MatrixRoundTrip_Double.h5", H5F_ACC_TRUNC);
            EigenHDF5::save(file, "double_matrix", mat);
        }
        {
            H5::H5File file("test_MatrixRoundTrip_Double.h5", H5F_ACC_RDONLY);
            EigenHDF5::load(file, "double_matrix", mat2);
        }
        ASSERT_PRED_FORMAT2(assert_same, mat, mat2);
    }

**Comment by Gjacquenot** [comment]
From what I understand, code is ok. CI is broken.

One used vivid ubuntu to access hdf5 1.8.13, but CI is broken when using vivid. I need more time to have it worked

**Pull request merged**
